import {
  LayoutDashboard,
  Inbox,
  Contact,
  Target,
  Megaphone,
  FileText,
  Zap,
  MessageCircle,
  Users,
  BarChart3,
  CreditCard,
  Plug,
  Code2,
  Settings,
  type LucideIcon,
} from "lucide-react";

export const DASHBOARD_NAV: ReadonlyArray<{ href: string; label: string; icon: LucideIcon }> = [
  { href: "/dashboard", label: "Overview", icon: LayoutDashboard },
  { href: "/dashboard/inbox", label: "Inbox", icon: Inbox },
  { href: "/dashboard/contacts", label: "Contacts", icon: Contact },
  { href: "/dashboard/leads", label: "Leads", icon: Target },
  { href: "/dashboard/campaigns", label: "Campaigns", icon: Megaphone },
  { href: "/dashboard/templates", label: "Templates", icon: FileText },
  { href: "/dashboard/automation", label: "Automation", icon: Zap },
  { href: "/dashboard/whatsapp", label: "WhatsApp", icon: MessageCircle },
  { href: "/dashboard/team", label: "Team", icon: Users },
  { href: "/dashboard/analytics", label: "Analytics", icon: BarChart3 },
  { href: "/dashboard/billing", label: "Billing", icon: CreditCard },
  { href: "/dashboard/integrations", label: "Integrations", icon: Plug },
  { href: "/dashboard/api", label: "API", icon: Code2 },
  { href: "/dashboard/settings", label: "Settings", icon: Settings },
];
